name: Build TypeScript docs

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install API Extractor
        run: npm install -g @microsoft/api-extractor

      - name: Run API Extractor
        run: |
          cd config
          api-extractor run --local --verbose

      - name: Clone API Documenter fork
        run: git clone https://github.com/ericaxu/rushstack-obsidian.git

      - name: Install Rush
        run: npm install -g @microsoft/rush

      - name: Build Rushstack
        run: |
          cd ./rushstack-obsidian
          rush update --bypass-policy
          rush build

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Build API Documenter
        run: |
          ./apps/api-documenter/bin/api-documenter markdown --output ../../en/Reference/TypeScript\ API
